### ISSUE TITLE
Env call should be capitalised

### ISSUE THREAD

**Issue by williamrenfrew** [SynergiTech/fuelphp-postal#5]
https://github.com/SynergiTech/fuelphp-postal/blob/58b65112da7a8973dc6f3cb1b4b6719e6f75427b/classes/postal.php#L60

Other `getenv()` calls are using `EMAIL`, does this need to be the same?

**Comment by willpower232** [comment]
if its a problem, its been a problem since the package was initially created

**Comment by williamrenfrew** [comment]
Yup, its in the 'if $to is an array' catch so probably little used, but if capitalisation does effect env vars then I feel it should be corrected.

**Comment by Josh-G** [comment]
https://www.php.net/manual/en/function.getenv.php#122599
